---
- name: Generate JSON config file
  hosts: localhost
  vars:
    cluster_os_type: "{{ lookup('env', 'CLUSTER_OS_TYPE') }}"
    cluster_os_version: "{{ lookup('env', 'CLUSTER_OS_VERSION') }}"
    repo_config: "{{ lookup('env', 'REPO_CONFIG') }}"
    softwares: "{{ lookup('env', 'SOFTWARES') | from_json }}"
    bcm_roce: "{{ lookup('env', 'BCM_ROCE') | from_json }}"
    amdgpu: "{{ lookup('env', 'AMDGPU') | from_json }}"
    pytorch: "{{ lookup('env', 'PYTORCH') | from_json }}"
    tensorflow: "{{ lookup('env', 'TENSORFLOW') | from_json }}"
  tasks:
    - name: Render the JSON configuration file from template
      template:
        src: config_template.j2
        dest: /home/omnia/config.json
