---
- name: Generate JSON config file
  hosts: localhost
  vars:
    cluster_os_type: "{{ lookup('env', 'CLUSTER_OS_TYPE') }}"
    cluster_os_version: "{{ lookup('env', 'CLUSTER_OS_VERSION') }}"
    repo_config: "{{ lookup('env', 'REPO_CONFIG') }}"
    softwares: "{{ lookup('env', 'SOFTWARES') | from_json }}"
    bcm_roce_libraries: "{{ lookup('env', 'bcm_roce_libraries').split(',') }}"
    amdgpu_libraries: "{{ lookup('env', 'amdgpu_libraries').split(',') }}"
    pytorch_dependencies: "{{ lookup('env', 'pytorch_dependencies').split(',') }}"
    tensorflow_dependencies: "{{ lookup('env', 'tensorflow_dependencies').split(',') }}"
    version: "{{ lookup('env', 'version') | from_json }}"
  tasks:
    - name: Render the JSON configuration file from template
      debug:
        msg: "bcm_roce_libraries: {{ bcm_roce_libraries }}"

    - name: Render the JSON configuration file from template
      debug:
        msg: "softwares: softwares

    - name: Render the JSON configuration file from template
      template:
        src: config_template.j2
        dest: /home/omnia/config.json
