---
- name: Generate JSON config file
  hosts: localhost
  vars:
    cluster_os_type: "{{ lookup('env', 'CLUSTER_OS_TYPE') }}"
    cluster_os_version: "{{ lookup('env', 'CLUSTER_OS_VERSION') }}"
    repo_config: "{{ lookup('env', 'REPO_CONFIG') }}"
    softwares: "{{ lookup('env', 'SOFTWARES') | from_json }}"
    bcm_roce: "{{ lookup('env', 'BCM_ROCE') }}"
    amdgpu: "{{ lookup('env', 'AMDGPU') | from_json }}"
    pytorch: "{{ lookup('env', 'PYTORCH_DEPENDENCIES') | from_json }}"
    tensorflow: "{{ lookup('env', 'TENSORFLOW_DEPENDENCIES') | from_json }}"
    version: "{{ lookup('env', 'version') | from_json }}"
  tasks:
    - name: Render the JSON configuration file from template
      template:
        src: config_template.j2
        dest: /home/omnia/config.json


pytorch_dependencies: "{{ lookup('env', 'PYTORCH_DEPENDENCIES_JSON') | default('[]') | from_json }}"
    tensorflow_dependencies: "{{ lookup('env', 'TENSORFLOW_DEPENDENCIES_JSON') | default('[]') | from_json }}"
  tasks:

