- name: Local Repository Playbook
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    local_repo_config_json_file: "input/config/local_repo_config.json"
    Software_list: "{{ lookup('ansible.builtin.env', 'softwarelist').split(',') }}"
    versions: "{{ lookup('ansible.builtin.env', 'versions') }}"

  tasks:
    - name: generate input file using jinja2 as per input variables
      ansible.builtin.template:
        src: "{{ ansible_distribution | lower }}_local_repo_config.json.j2"
        dest: "{{ software_config_json_file }}"
