- name: Local Repository Playbook
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    software_config_json_file: "input/software_config.json"
    softwarelist: "{{ lookup('ansible.builtin.env', 'softwarelist').split('') }}"

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: generate input file using jinja2 as per input variables
      ansible.builtin.template:
        src: "{{ ansible_distribution | lower }}_software_config.json.j2"
        dest: "{{ software_config_json_file }}"
