- name: Local Repository Playbook
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    software_config_json_file: "input/software_config.json"
    softwares: "{{ lookup('ansible.builtin.env', 'softwares') }}" 
    cluster_os_type : "{{ lookup('ansible.builtin.env', 'cluster_os_type ') }}"
    cluster_os_version: "{{ lookup('ansible.builtin.env', 'cluster_os_version') }}"
    repo_config: "{{ lookup('ansible.builtin.env', 'repo_config') }}"
    bcm_roce: "{{ lookup('ansible.builtin.env', 'bcm_roce') }}"
    amdgpu: "{{ lookup('ansible.builtin.env', 'amdgpu') }}"
   


  tasks:
#    - name: Print all available facts
#      ansible.builtin.debug:
#        var: ansible_facts

    - name: generate input file using jinja2 as per input variables
      ansible.builtin.template:
        src: "{{ ansible_distribution | lower }}_software_config.json_bkp2.j2"
        dest: "{{ software_config_json_file }}"
